#!/bin/bash
PROJECT_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/.."
DOCKER_COMPOSE_FILE="${PROJECT_ROOT}/docker-compose.yml"
SETTINGS_FILE="${PROJECT_ROOT}/app/settings.py"

if [ "$EUID" -eq 0 ]; then 
    echo "Error: Blackpill should not be run as root."
    exit 1
fi

if [[ ! -d "${PROJECT_ROOT}/app/media" ]]; then
    echo "Add media folder:"
    mkdir "${PROJECT_ROOT}/app/media"
    exit 1
fi

if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo "Settings file not found."
    exit 1
fi

docker compose \
  -f $DOCKER_COMPOSE_FILE \
  up --build --remove-orphans $@
